///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

import 'dart:convert';

List<CovidModel> covidModelFromJson(String str) =>
    List<CovidModel>.from(json.decode(str).map((x) => CovidModel.fromJson(x)));

String covidModelToJson(List<CovidModel> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class CovidModel {
/*
{
  "date": 20210307,
  "states": 56,
  "positive": 28756489,
  "negative": 74582825,
  "pending": 11808,
  "hospitalizedCurrently": 40199,
  "hospitalizedCumulative": 776361,
  "inIcuCurrently": 8134,
  "inIcuCumulative": 45475,
  "onVentilatorCurrently": 2802,
  "onVentilatorCumulative": 4281,
  "dateChecked": "2021-03-07T24:00:00Z",
  "death": 515151,
  "hospitalized": 776361,
  "totalTestResults": 363825123,
  "lastModified": "2021-03-07T24:00:00Z",
  "recovered": null,
  "total": 0,
  "posNeg": 0,
  "deathIncrease": 842,
  "hospitalizedIncrease": 726,
  "negativeIncrease": 131835,
  "positiveIncrease": 41835,
  "totalTestResultsIncrease": 1170059,
  "hash": "a80d0063822e251249fd9a44730c49cb23defd83"
}
*/

  int? date;
  int? states;
  int? positive;
  int? negative;
  int? pending;
  int? hospitalizedCurrently;
  int? hospitalizedCumulative;
  int? inIcuCurrently;
  int? inIcuCumulative;
  int? onVentilatorCurrently;
  int? onVentilatorCumulative;
  String? dateChecked;
  int? death;
  int? hospitalized;
  int? totalTestResults;
  String? lastModified;
  String? recovered;
  int? total;
  int? posNeg;
  int? deathIncrease;
  int? hospitalizedIncrease;
  int? negativeIncrease;
  int? positiveIncrease;
  int? totalTestResultsIncrease;
  String? hash;

  CovidModel({
    this.date,
    this.states,
    this.positive,
    this.negative,
    this.pending,
    this.hospitalizedCurrently,
    this.hospitalizedCumulative,
    this.inIcuCurrently,
    this.inIcuCumulative,
    this.onVentilatorCurrently,
    this.onVentilatorCumulative,
    this.dateChecked,
    this.death,
    this.hospitalized,
    this.totalTestResults,
    this.lastModified,
    this.recovered,
    this.total,
    this.posNeg,
    this.deathIncrease,
    this.hospitalizedIncrease,
    this.negativeIncrease,
    this.positiveIncrease,
    this.totalTestResultsIncrease,
    this.hash,
  });
  CovidModel.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toInt();
    states = json['states']?.toInt();
    positive = json['positive']?.toInt();
    negative = json['negative']?.toInt();
    pending = json['pending']?.toInt();
    hospitalizedCurrently = json['hospitalizedCurrently']?.toInt();
    hospitalizedCumulative = json['hospitalizedCumulative']?.toInt();
    inIcuCurrently = json['inIcuCurrently']?.toInt();
    inIcuCumulative = json['inIcuCumulative']?.toInt();
    onVentilatorCurrently = json['onVentilatorCurrently']?.toInt();
    onVentilatorCumulative = json['onVentilatorCumulative']?.toInt();
    dateChecked = json['dateChecked']?.toString();
    death = json['death']?.toInt();
    hospitalized = json['hospitalized']?.toInt();
    totalTestResults = json['totalTestResults']?.toInt();
    lastModified = json['lastModified']?.toString();
    recovered = json['recovered']?.toString();
    total = json['total']?.toInt();
    posNeg = json['posNeg']?.toInt();
    deathIncrease = json['deathIncrease']?.toInt();
    hospitalizedIncrease = json['hospitalizedIncrease']?.toInt();
    negativeIncrease = json['negativeIncrease']?.toInt();
    positiveIncrease = json['positiveIncrease']?.toInt();
    totalTestResultsIncrease = json['totalTestResultsIncrease']?.toInt();
    hash = json['hash']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['states'] = states;
    data['positive'] = positive;
    data['negative'] = negative;
    data['pending'] = pending;
    data['hospitalizedCurrently'] = hospitalizedCurrently;
    data['hospitalizedCumulative'] = hospitalizedCumulative;
    data['inIcuCurrently'] = inIcuCurrently;
    data['inIcuCumulative'] = inIcuCumulative;
    data['onVentilatorCurrently'] = onVentilatorCurrently;
    data['onVentilatorCumulative'] = onVentilatorCumulative;
    data['dateChecked'] = dateChecked;
    data['death'] = death;
    data['hospitalized'] = hospitalized;
    data['totalTestResults'] = totalTestResults;
    data['lastModified'] = lastModified;
    data['recovered'] = recovered;
    data['total'] = total;
    data['posNeg'] = posNeg;
    data['deathIncrease'] = deathIncrease;
    data['hospitalizedIncrease'] = hospitalizedIncrease;
    data['negativeIncrease'] = negativeIncrease;
    data['positiveIncrease'] = positiveIncrease;
    data['totalTestResultsIncrease'] = totalTestResultsIncrease;
    data['hash'] = hash;
    return data;
  }
}
